apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mosquitto
  namespace: default
spec:
  hosts:
    - mosquitto.dev.local
  gateways:
    - default-gateway
  tcp:
    - match:
        - port: 1883
      route:
        - destination:
            host: mosquitto
            port:
              number: 1883
