- name: Install microk8s
  become: yes
  community.general.snap:
    name: microk8s
    classic: yes
    channel: 1.21/stable

- name: Adding user {{ ansible_user }} to microk8s group
  user:
    name: '{{ ansible_user }}'
    groups:
      - microk8s
    append: yes

- name: Recursively change ownership of kube folder
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    recurse: yes
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Install python3-pip
  become: yes
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install OpenShift Python client
  pip:
    name: openshift
    state: present
