apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kafka-rest
  namespace: default
spec:
  hosts:
    - 'kafka-rest.{{ hostname }}'
  gateways:
    - default-gateway
  http:
    - route:
        - destination:
            port:
              number: 8082
            host: confluent-cp-kafka-rest
