apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nifi
  namespace: default
spec:
  hosts:
    - 'nifi.{{ hostname }}'
  gateways:
    - default-gateway
  http:
    - route:
        - destination:
            port:
              number: 8080
            host: nifi
