- name: Install ZooKeeper chart with custom values
  community.kubernetes.helm:
    name: zookeeper
    namespace: default
    chart_ref: bitnami/zookeeper
    values: "{{ lookup('file', 'values.yaml') | from_yaml }}"
    atomic: yes
    update_repo_cache: yes
    binary_path: '{{ helm_binary }}'
