apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: spark
  namespace: default
spec:
  hosts:
    - 'spark.{{ hostname }}'
  gateways:
    - default-gateway
  http:
    - route:
        - destination:
            port:
              number: 80
            host: spark-master-svc
