apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jupyterhub
  namespace: default
spec:
  hosts:
    - 'jupyter.{{ hostname }}'
  gateways:
    - default-gateway
  tls:
    - match:
        - port: 443
          sniHosts:
            - 'jupyter.{{ hostname }}'
      route:
        - destination:
            host: proxy-public
            port:
              number: 443
