persistence:
  nameNode:
    enabled: false
    storageClass:
    accessMode: ReadWriteOnce
    size: 5Gi
  dataNode:
    enabled: false
    storageClass:
    accessMode: ReadWriteOnce
    size: 10Gi

conf:
  hdfsSite:
    dfs.permissions.enabled: 'false'

#postInstallCommands:
#  - hdfs dfs -mkdir /nifi
#  - hdfs dfs -chown nifi /nifi
#  - hdfs dfs -chmod 0755 /nifi
#  - hdfs dfs -ls /
