apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hdfs
  namespace: default
spec:
  hosts:
    - 'hdfs.{{ hostname }}'
  gateways:
    - default-gateway
  http:
    - route:
        - destination:
            port:
              number: 50070
            host: hdfs
